name: proste_lint
description: Provide default lint, plug and play, convenient for team coordination.
version: 1.1.1
homepage: https://github.com/xyhxx/proste_lint

environment:
  sdk: ">=2.12.0 <3.0.0"